package f.cking.software.data.helpers

import android.content.Context
import timber.log.Timber

/**
 * Lookup of IEEE OUI (24-bit Organisationally Unique Identifier) → assigned organisation name.
 *
 * Asset source: [https://standards-oui.ieee.org/oui/oui.csv] regenerated by the build pipeline.
 * Only the MA-L registry (24-bit OUI blocks) is bundled; MA-M and MA-S are smaller blocks that
 * narrow into a sub-OUI and aren't relevant for Bluetooth / WiFi MAC vendor identification.
 *
 * Used for two purposes:
 *  1. **Address-type classification.** When the platform doesn't expose
 *     `BluetoothDevice.getAddressType()` (Android < 15), the bit-pattern heuristic in
 *     [BuildExtendedAddressInfoInteractor] can't distinguish Static-Random from Public for
 *     `0b11`-prefixed addresses, nor NRPA from Public for `0b00`-prefixed ones. An IEEE-
 *     registered OUI is strong evidence the address is Public — the random-address space
 *     is a 46-bit pool with no relation to IEEE OUI assignments, so the chance of a random
 *     address happening to match an assigned 24-bit OUI is ~1 in 280, and the false-positive
 *     cost (misclassifying an Apple/Microsoft RPA as Public) is rare anyway.
 *  2. **Manufacturer attribution.** When a device's advertisement carries no
 *     manufacturer-specific-data company id (or only a generic one like 0xFFFF), the OUI of
 *     a public BDADDR is the next-best vendor signal. Surfaced on the Device Details screen
 *     as a "Manufacturer" line when MSD didn't supply one.
 *
 * Address-display convention: BLE/BT addresses are shown big-endian as `AA:BB:CC:DD:EE:FF`,
 * and the IEEE OUI is the first three bytes (`AA:BB:CC`) of that display. Internally we
 * encode it as a 24-bit `Int` (`(AA << 16) | (BB << 8) | CC`) to match the format already
 * used in [VendorRegistry] and [VendorIdentifier.parseOui].
 */
class OuiRepository(
    private val appContext: Context,
) {

    @Volatile
    private var index: Map<Int, String>? = null

    /** Look up [oui] (24-bit `Int`). Returns null when the OUI isn't IEEE-assigned. */
    fun lookup(oui: Int): String? = ensureLoaded()[oui]

    /**
     * Convenience: parse a `AA:BB:CC:DD:EE:FF` address (or any string with at least three
     * colon-separated hex pairs) into the 24-bit OUI int and look it up.
     */
    fun lookupByAddress(address: String): String? {
        val parts = address.split(':')
        if (parts.size < 3) return null
        val a = parts[0].toIntOrNull(16) ?: return null
        val b = parts[1].toIntOrNull(16) ?: return null
        val c = parts[2].toIntOrNull(16) ?: return null
        return lookup((a shl 16) or (b shl 8) or c)
    }

    /** True when the address's OUI is IEEE-assigned. Cheap path when only a yes/no is needed. */
    fun isAssigned(address: String): Boolean = lookupByAddress(address) != null

    private fun ensureLoaded(): Map<Int, String> {
        index?.let { return it }
        synchronized(this) {
            index?.let { return it }
            val loaded = try {
                appContext.assets.open(ASSET_NAME).use { stream ->
                    parse(stream.bufferedReader().readText())
                }
            } catch (e: Throwable) {
                Timber.tag(TAG).e(e, "Failed to load OUI asset")
                emptyMap()
            }
            index = loaded
            return loaded
        }
    }

    private fun parse(text: String): Map<Int, String> {
        val out = HashMap<Int, String>(40_000)
        for (line in text.lineSequence()) {
            if (line.isEmpty()) continue
            val pipe = line.indexOf('|')
            if (pipe != 6) continue // OUI is always 6 hex chars
            val oui = line.substring(0, 6).toIntOrNull(16) ?: continue
            val name = line.substring(pipe + 1).trim()
            if (name.isEmpty()) continue
            out[oui] = name
        }
        return out
    }

    companion object {
        private const val ASSET_NAME = "ieee_oui_ma_l.txt"
        private const val TAG = "OuiRepository"
    }
}
